### ISSUE TITLE
Missing polyfills after latest aurelia update

### ISSUE THREAD

**Issue by bellstrand** [oribella/aurelia-sortable#13]
After Aurelia removed its dependency on core-js we're missing some polyfills.

"Uncaught TypeError: Object.getOwnPropertyDescriptors is not a function"

**Comment by stoffeastrom** [comment]
I guess it's coming from the [oribella-framework](https://github.com/oribella/framework/blob/master/src/registry.js#L37-L43)?

**Comment by stoffeastrom** [comment]
That should not have been used. Need to rewrite it using
`Object.getOwnPropertyDescriptor`

**Comment by bellstrand** [comment]
Yeah, oribella-framework. registry.js

**Comment by stoffeastrom** [comment]
Released a new patch version `oribella-framework@0.4.1`. Update and let me know that it works

**Comment by stoffeastrom** [comment]
Oh seems like I have to update `aurelia-sortable` to latest `oribella-default-gestures`.

**Comment by stoffeastrom** [comment]
Should be fixed in `0.6.0`

**Comment by bellstrand** [comment]
I think you forgot to update oribella-framework@0.4.1's dist, I can see that you have changed the source code but when downloaded with jspm I get the old dist. I can also see that the latest version of oribella-swipe is throwing errors, looks like the dist there still includes es6 code that's not transpiled.

**Comment by stoffeastrom** [comment]
Thanks for reporting. Will look into it

**Comment by stoffeastrom** [comment]
Yes I can see that the `dist` is not updated for `oribella-framework`. However regarding the `oribella-swipe`I can't see that the `dist` is wrong. Will get a patch out later tonight

**Comment by stoffeastrom** [comment]
Hmm.. now I see it.. weird it looked like amd but it has `class` defined

**Comment by bellstrand** [comment]
Yeah, it caused some trouble :P, anyhow was looking abit at your libraries (oribella-framework, and oribella-swipe) and tried to build them myself, but was unable to run your "build, test, etc" commands specified in package.json. What are you using for these commands work?

I've tried to do this => "npm install; npm run build;". Do I need so install something that ain't specified in package.json to get these to work properly? would be nice so that I could fix the problems myself and create some pull requests for you :)

**Comment by stoffeastrom** [comment]
Tried building on my work laptop with windows and I realized I haven't enabled that scenario ;). Will fix that so it's easier.

PR's welcome. 

We have to update the `oribella-dev` commands to add `.cmd` on windows something like

```javascript
if ( process.platform === "win32" ) {
  babelPath += ".cmd";
}
```

**Comment by stoffeastrom** [comment]
So if you clone the `dev` repo and add that and run `npm run build`

go into `swipe`
`npm link ../dev`
`npm run build`

**Comment by stoffeastrom** [comment]
Released new patch versions for `oribella-framework`, `oribella-swipe`.

**Comment by bellstrand** [comment]
Works great now!

**Comment by stoffeastrom** [comment]
Nice! Sorry about missing updating the `dist`! I will try to get things up and running on windows and how it should be used.
